name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions.
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
- uses: 'google-github-actions/auth@v3'
  with:
    project_id: 'dialogflowcx-handson'
    workload_identity_provider: 'projects/692897809117/locations/global/workloadIdentityPools/github/providers/my-repo' # "projects/123456789/locations/global/workloadIdentityPools/github/providers/my-repo"

